from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("3D LED Framework")
        #MainWindow.setGeometry(400, 200, 1000, 600)
        MainWindow.resize(819, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(0, 510, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setObjectName("startButton")
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(140, 510, 141, 41))
        self.pauseButton.setObjectName("pauseButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(280, 510, 141, 41))
        self.stopButton.setObjectName("stopButton")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(420, 510, 141, 41))
        self.openButton.setObjectName("openButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 480, 551, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.blueVerticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.blueVerticalSlider.setGeometry(QtCore.QRect(780, 390, 22, 160))
        self.blueVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.blueVerticalSlider.setObjectName("blueVerticalSlider")
        self.greenVerticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.greenVerticalSlider.setGeometry(QtCore.QRect(720, 390, 22, 160))
        self.greenVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.greenVerticalSlider.setObjectName("greenVerticalSlider")
        self.redVerticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.redVerticalSlider.setGeometry(QtCore.QRect(660, 390, 22, 160))
        self.redVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.redVerticalSlider.setObjectName("redVerticalSlider")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(660, 10, 141, 41))
        self.loadButton.setObjectName("loadButton")
        self.readyAnimationBox = QtWidgets.QComboBox(self.centralwidget)
        self.readyAnimationBox.setGeometry(QtCore.QRect(660, 60, 141, 21))
        self.readyAnimationBox.setObjectName("readyAnimationBox")
        self.redLabel = QtWidgets.QLabel(self.centralwidget)
        self.redLabel.setGeometry(QtCore.QRect(640, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.redLabel.setFont(font)
        self.redLabel.setObjectName("redLabel")
        self.greenLabel = QtWidgets.QLabel(self.centralwidget)
        self.greenLabel.setGeometry(QtCore.QRect(700, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.greenLabel.setFont(font)
        self.greenLabel.setObjectName("greenLabel")
        self.blueLabel = QtWidgets.QLabel(self.centralwidget)
        self.blueLabel.setGeometry(QtCore.QRect(760, 530, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.blueLabel.setFont(font)
        self.blueLabel.setObjectName("blueLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3D LED Framework"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.openButton.setText(_translate("MainWindow", "Open file"))
        self.loadButton.setText(_translate("MainWindow", "Load animation"))
        self.redLabel.setText(_translate("MainWindow", "R"))
        self.greenLabel.setText(_translate("MainWindow", "G"))
        self.blueLabel.setText(_translate("MainWindow", "B"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
